Ported @zapjs/curve and its types;
zapproject/zappy pull request #29
Opened 2021-02-10 15:44 UTC by acemasterjb

Should note that python does now have switch statements, a dict with lambda values was used instead;

BigNumbers are integers by default in python;

Curve/regex holds regex pattern for Curve/curve

---

Tackles issue #8 

needs to be mock tested

2021-02-10 15:47 UTC, superposition requested changes

2021-02-10 15:47 UTC, superposition commented on Curve/types.py
> +    power: int or float
please include tests before submission

2021-02-10 15:52 UTC, acemasterjb commented
@andrew-fleming can you help me out with this change?

2021-02-10 16:13 UTC, andrew-fleming commented
@acemasterjb yeah, I'll take a look

2021-02-15 22:46 UTC, acemasterjb commented
Curve\test\Curve_test: Added testing via pytests; Tested 1 case for checkValidity 

will add more tests soon.

2021-02-16 10:04 UTC, acemasterjb commented
This pull also removes the cloned web3

2021-02-18 01:42 UTC, superposition commented
hey resolve these conflicts!

2021-02-18 01:44 UTC, merged